-- MySQL Script generated by MySQL Workbench
-- 10/15/15 15:41:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TipoPlanta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoPlanta` (
  `idTipoPlanta` INT NOT NULL AUTO_INCREMENT,
  `NombreTipoPlanta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoPlanta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Planta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Planta` (
  `idPlanta` INT NOT NULL AUTO_INCREMENT,
  `NombreP` VARCHAR(45) NOT NULL,
  `Altura` INT NOT NULL,
  `Costo` FLOAT NOT NULL,
  `Status` VARCHAR(10) NOT NULL,
  `DescBaja` VARCHAR(255) NOT NULL,
  `Cantidad` VARCHAR(45) NOT NULL,
  `Color` VARCHAR(45) NOT NULL,
  `Imagen` VARCHAR(255) NOT NULL,
  `idTipoPlanta` INT NOT NULL,
  PRIMARY KEY (`idPlanta`),
  INDEX `fk_Planta_TipoPlanta1_idx` (`idTipoPlanta` ASC),
  CONSTRAINT `fk_Planta_TipoPlanta1`
    FOREIGN KEY (`idTipoPlanta`)
    REFERENCES `mydb`.`TipoPlanta` (`idTipoPlanta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoUsuario` (
  `idTipoCliente` INT NOT NULL AUTO_INCREMENT,
  `NombreTipoUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `NombreCompleto` VARCHAR(60) NOT NULL,
  `Direccion` VARCHAR(155) NOT NULL,
  `Telefono` VARCHAR(25) NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  `NumTarjeta` VARCHAR(46) NULL,
  `NumSecreTarjeta` VARCHAR(3) NULL,
  `User` VARCHAR(45) NOT NULL,
  `Pass` VARCHAR(45) NOT NULL,
  `Sexo` VARCHAR(2) NOT NULL,
  `TipoUsuario_idTipoCliente` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_TipoUsuario1_idx` (`TipoUsuario_idTipoCliente` ASC),
  CONSTRAINT `fk_Usuario_TipoUsuario1`
    FOREIGN KEY (`TipoUsuario_idTipoCliente`)
    REFERENCES `mydb`.`TipoUsuario` (`idTipoCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carrito` (
  `Planta_idPlanta` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `NombreP` VARCHAR(45) NOT NULL,
  `Pienzas` INT NOT NULL,
  `CostoUni` FLOAT NOT NULL,
  `CostoTotal` FLOAT NOT NULL,
  PRIMARY KEY (`Planta_idPlanta`, `Usuario_idUsuario`),
  INDEX `fk_Planta_has_Usuario_Usuario1_idx` (`Usuario_idUsuario` ASC),
  INDEX `fk_Planta_has_Usuario_Planta1_idx` (`Planta_idPlanta` ASC),
  CONSTRAINT `fk_Planta_has_Usuario_Planta1`
    FOREIGN KEY (`Planta_idPlanta`)
    REFERENCES `mydb`.`Planta` (`idPlanta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Planta_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Venta` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `Piezas` INT NOT NULL,
  `Costo` FLOAT NOT NULL,
  `CostoTotal` FLOAT NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `idPlanta` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `Carrito_idPlanta` INT NOT NULL,
  `Carrito_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `fk_Venta_Planta1_idx` (`idPlanta` ASC),
  INDEX `fk_Venta_Usuario1_idx` (`idUsuario` ASC),
  INDEX `fk_Venta_Carrito1_idx` (`Carrito_idPlanta` ASC, `Carrito_idUsuario` ASC),
  CONSTRAINT `fk_Venta_Planta1`
    FOREIGN KEY (`idPlanta`)
    REFERENCES `mydb`.`Planta` (`idPlanta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_Carrito1`
    FOREIGN KEY (`Carrito_idPlanta` , `Carrito_idUsuario`)
    REFERENCES `mydb`.`Carrito` (`Planta_idPlanta` , `Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `idTipoPlanta` INT NOT NULL,
  PRIMARY KEY (`idProveedor`),
  INDEX `fk_Proveedor_TipoPlanta1_idx` (`idTipoPlanta` ASC),
  CONSTRAINT `fk_Proveedor_TipoPlanta1`
    FOREIGN KEY (`idTipoPlanta`)
    REFERENCES `mydb`.`TipoPlanta` (`idTipoPlanta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DetalleVentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DetalleVentas` (
  `idDetalleVentas` INT NOT NULL AUTO_INCREMENT,
  `TotalVenta` FLOAT NOT NULL,
  `idVenta` INT NOT NULL,
  INDEX `fk_ReporteVenta_Venta1_idx` (`idVenta` ASC),
  PRIMARY KEY (`idDetalleVentas`),
  CONSTRAINT `fk_ReporteVenta_Venta1`
    FOREIGN KEY (`idVenta`)
    REFERENCES `mydb`.`Venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
